#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-icu4j
Version  : 56.1
Release  : 6
URL      : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/56.1/icu4j-56.1.jar
Source0  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/56.1/icu4j-56.1.jar
Source1  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.jar
Source2  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.pom
Source3  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1/icu4j-54.1.jar
Source4  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1/icu4j-54.1.pom
Source5  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/56.1/icu4j-56.1.pom
Source6  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/58.1/icu4j-58.1.jar
Source7  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/58.1/icu4j-58.1.pom
Source8  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/58.2/icu4j-58.2.jar
Source9  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/58.2/icu4j-58.2.pom
Source10  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/59.1/icu4j-59.1.jar
Source11  : https://repo1.maven.org/maven2/com/ibm/icu/icu4j/59.1/icu4j-59.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : ICU
Requires: mvn-icu4j-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-icu4j package.
Group: Data

%description data
data components for the mvn-icu4j package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/56.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/56.1/icu4j-56.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/2.6.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/2.6.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/54.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/54.1/icu4j-54.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/54.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/54.1/icu4j-54.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/56.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/56.1/icu4j-56.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.1
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.1/icu4j-58.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.1/icu4j-58.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.2
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.2/icu4j-58.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.2/icu4j-58.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/59.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/59.1/icu4j-59.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/59.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/com/ibm/icu/icu4j/59.1/icu4j-59.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.jar
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.pom
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/54.1/icu4j-54.1.jar
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/54.1/icu4j-54.1.pom
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/56.1/icu4j-56.1.jar
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/56.1/icu4j-56.1.pom
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.1/icu4j-58.1.jar
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.1/icu4j-58.1.pom
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.2/icu4j-58.2.jar
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/58.2/icu4j-58.2.pom
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/59.1/icu4j-59.1.jar
/usr/share/java/.m2/repository/com/ibm/icu/icu4j/59.1/icu4j-59.1.pom
